"""
Policy-as-Code Generator
=========================
Generates executable Rego and XACML from resolved policies.
"""

from typing import List, Dict, Optional
import json
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from models.cpm import CPMRule, Effect


class RegoGenerator:
    """
    Generates Open Policy Agent (OPA) Rego policies from CPM rules.
    """
    
    TEMPLATE_HEADER = '''# Auto-generated Rego Policy
# Generated by PolicyGuard Conflict Detection Pipeline
# Framework: {framework}

package {package_name}

import rego.v1

default allow := false
default deny := false

'''
    
    def __init__(self, package_name: str = "policy"):
        self.package_name = package_name
    
    def generate_rule(self, rule: CPMRule) -> str:
        """Generate single Rego rule"""
        lines = []
        
        # Rule comment
        lines.append(f"# Rule: {rule.rule_id} (from {rule.framework_origin})")
        lines.append(f"# Priority: {rule.priority}")
        
        # Effect-based rule name
        effect_name = "allow" if rule.effect == Effect.PERMIT else "deny"
        
        # Build conditions
        conditions = []
        
        # Subject conditions
        if rule.subject.type:
            conditions.append(f'input.subject.type == "{rule.subject.type}"')
        
        if rule.subject.roles:
            for role in rule.subject.roles:
                conditions.append(f'"{role}" in input.subject.roles')
        
        # Action condition
        conditions.append(f'input.action == "{rule.action}"')
        
        # Resource conditions
        if rule.resource.type:
            conditions.append(f'input.resource.type == "{rule.resource.type}"')
        
        if rule.resource.identifiers:
            ids_str = ", ".join([f'"{r}"' for r in rule.resource.identifiers])
            conditions.append(f"input.resource.id in [{ids_str}]")
        
        # Environment conditions
        for key, value in rule.environment.conditions.items():
            if isinstance(value, bool):
                conditions.append(f"input.environment.{key} == {str(value).lower()}")
            elif isinstance(value, (int, float)):
                conditions.append(f"input.environment.{key} == {value}")
            else:
                conditions.append(f'input.environment.{key} == "{value}"')
        
        # Build rule body
        lines.append(f"{effect_name} if {{")
        for condition in conditions:
            lines.append(f"    {condition}")
        lines.append("}")
        
        # Add obligations if present
        if rule.obligations:
            lines.append("")
            lines.append(f"# Obligations for {rule.rule_id}")
            lines.append(f"obligations_{rule.rule_id.lower()} := {{")
            for obl in rule.obligations:
                lines.append(f'    "{obl}",')
            lines.append("}")
        
        return "\n".join(lines)
    
    def generate(self, rules: List[CPMRule], framework: str = "PolicyGuard") -> str:
        """Generate complete Rego policy file"""
        output = self.TEMPLATE_HEADER.format(
            framework=framework,
            package_name=self.package_name
        )
        
        for rule in rules:
            output += self.generate_rule(rule) + "\n\n"
        
        # Add helper rules
        output += '''
# Decision logic with priority
final_decision := decision if {
    allow
    not deny
    decision := "allow"
}

final_decision := decision if {
    deny
    not allow
    decision := "deny"
}

final_decision := decision if {
    allow
    deny
    # Conflict detected - should not happen after resolution
    decision := "conflict"
}

final_decision := "deny" if {
    not allow
    not deny
}
'''
        
        return output


class XACMLGenerator:
    """
    Generates XACML 3.0 policies from CPM rules.
    """
    
    TEMPLATE_HEADER = '''<?xml version="1.0" encoding="UTF-8"?>
<PolicySet xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           PolicySetId="{policy_set_id}"
           Version="1.0"
           PolicyCombiningAlgId="urn:oasis:names:tc:xacml:3.0:policy-combining-algorithm:deny-overrides">
    <Description>Auto-generated XACML Policy Set from PolicyGuard</Description>
    <Target/>
'''
    
    TEMPLATE_FOOTER = '''</PolicySet>
'''
    
    def __init__(self, policy_set_id: str = "PolicyGuardPolicySet"):
        self.policy_set_id = policy_set_id
    
    def generate_rule(self, rule: CPMRule, indent: int = 8) -> str:
        """Generate single XACML rule"""
        ind = " " * indent
        lines = []
        
        lines.append(f'{ind}<Rule RuleId="{rule.rule_id}" Effect="{rule.effect.value}">')
        lines.append(f'{ind}    <Description>From framework: {rule.framework_origin}, Priority: {rule.priority}</Description>')
        
        # Target
        lines.append(f'{ind}    <Target>')
        
        # Subject match
        if rule.subject.type or rule.subject.roles:
            lines.append(f'{ind}        <AnyOf>')
            lines.append(f'{ind}            <AllOf>')
            if rule.subject.type:
                lines.append(f'{ind}                <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">')
                lines.append(f'{ind}                    <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">{rule.subject.type}</AttributeValue>')
                lines.append(f'{ind}                    <AttributeDesignator Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" AttributeId="subject-type" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>')
                lines.append(f'{ind}                </Match>')
            lines.append(f'{ind}            </AllOf>')
            lines.append(f'{ind}        </AnyOf>')
        
        # Resource match
        if rule.resource.type:
            lines.append(f'{ind}        <AnyOf>')
            lines.append(f'{ind}            <AllOf>')
            lines.append(f'{ind}                <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">')
            lines.append(f'{ind}                    <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">{rule.resource.type}</AttributeValue>')
            lines.append(f'{ind}                    <AttributeDesignator Category="urn:oasis:names:tc:xacml:3.0:attribute-category:resource" AttributeId="resource-type" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>')
            lines.append(f'{ind}                </Match>')
            lines.append(f'{ind}            </AllOf>')
            lines.append(f'{ind}        </AnyOf>')
        
        # Action match
        lines.append(f'{ind}        <AnyOf>')
        lines.append(f'{ind}            <AllOf>')
        lines.append(f'{ind}                <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">')
        lines.append(f'{ind}                    <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">{rule.action}</AttributeValue>')
        lines.append(f'{ind}                    <AttributeDesignator Category="urn:oasis:names:tc:xacml:3.0:attribute-category:action" AttributeId="action-id" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>')
        lines.append(f'{ind}                </Match>')
        lines.append(f'{ind}            </AllOf>')
        lines.append(f'{ind}        </AnyOf>')
        
        lines.append(f'{ind}    </Target>')
        
        # Obligations
        if rule.obligations:
            lines.append(f'{ind}    <ObligationExpressions>')
            for obl in rule.obligations:
                lines.append(f'{ind}        <ObligationExpression ObligationId="{obl}" FulfillOn="{rule.effect.value}"/>')
            lines.append(f'{ind}    </ObligationExpressions>')
        
        lines.append(f'{ind}</Rule>')
        
        return "\n".join(lines)
    
    def generate(self, rules: List[CPMRule]) -> str:
        """Generate complete XACML policy set"""
        output = self.TEMPLATE_HEADER.format(policy_set_id=self.policy_set_id)
        
        # Group rules by framework
        by_framework = {}
        for rule in rules:
            fw = rule.framework_origin
            if fw not in by_framework:
                by_framework[fw] = []
            by_framework[fw].append(rule)
        
        # Generate policy per framework
        for framework, fw_rules in by_framework.items():
            output += f'''    <Policy PolicyId="{framework}_Policy" Version="1.0"
            RuleCombiningAlgId="urn:oasis:names:tc:xacml:3.0:rule-combining-algorithm:deny-overrides">
        <Target/>
'''
            for rule in fw_rules:
                output += self.generate_rule(rule) + "\n"
            
            output += "    </Policy>\n"
        
        output += self.TEMPLATE_FOOTER
        
        return output


class TestCaseGenerator:
    """
    Generates executable test cases from witness requests.
    """
    
    def generate_opa_test(self, witness: Dict, test_name: str = "conflict_test") -> str:
        """Generate OPA test case from witness"""
        request = witness.get("request", {})
        conflict = witness.get("conflict", {})
        
        test = f'''# Test case: {test_name}
# Generated from conflict witness

test_{test_name} if {{
    input := {{
        "subject": {{
            "type": "{request.get('subject', 'user')}",
            "roles": {json.dumps(request.get('roles', []))}
        }},
        "action": "{request.get('action', 'read')}",
        "resource": {{
            "type": "{request.get('resource_type', 'data')}",
            "id": "{request.get('resource', 'resource')}"
        }},
        "environment": {json.dumps(request.get('environment', {{}}))}
    }}
    
    # This request should produce a definitive decision
    # Original conflict: {conflict.get('rule_i', 'rule_i')} ({conflict.get('effect_i', 'effect')}) vs {conflict.get('rule_j', 'rule_j')} ({conflict.get('effect_j', 'effect')})
    final_decision != "conflict"
}}
'''
        return test
    
    def generate_json_test_case(self, witness: Dict) -> Dict:
        """Generate JSON test case from witness"""
        request = witness.get("request", {})
        
        return {
            "name": f"witness_{witness.get('conflict', {}).get('rule_i', 'test')}",
            "input": {
                "subject": {
                    "type": request.get("subject", "user"),
                    "roles": request.get("roles", [])
                },
                "action": request.get("action", "read"),
                "resource": {
                    "type": request.get("resource_type", "data"),
                    "id": request.get("resource", "resource")
                },
                "environment": request.get("environment", {})
            },
            "expected_decision": "allow_or_deny",  # Should not be "conflict"
            "description": f"Witness request for conflict between {witness.get('conflict', {}).get('rule_i', 'rule_i')} and {witness.get('conflict', {}).get('rule_j', 'rule_j')}"
        }


# ============================================================
# DEMONSTRATION: Policy-as-Code Generation
# ============================================================

def demonstrate_code_generation():
    """
    Demonstrates policy-as-code generation.
    """
    from models.cpm import CPMNormalizer
    
    print("=" * 70)
    print("POLICY-AS-CODE GENERATION DEMONSTRATION")
    print("=" * 70)
    
    # Sample resolved policies
    normalizer = CPMNormalizer()
    
    sample_rules = [
        {
            "rule_id": "GDPR_001",
            "subject": {"type": "processor", "roles": ["data_processor"]},
            "action": "export",
            "resource": {"type": "personal_data", "identifiers": ["export_api"]},
            "environment": {"consent_valid": True},
            "effect": "Permit",
            "obligations": ["require_audit_log", "require_encryption"],
        },
        {
            "rule_id": "PSD2_001",
            "subject": {"type": "customer", "roles": ["user", "account_holder"]},
            "action": "read",
            "resource": {"type": "account_data", "identifiers": ["balance_api", "transactions_api"]},
            "environment": {"authenticated": True, "sca_verified": True},
            "effect": "Permit",
        },
        {
            "rule_id": "SECURITY_001",
            "subject": {"type": "user", "roles": ["guest"]},
            "action": "read",
            "resource": {"type": "personal_data", "identifiers": []},
            "environment": {},
            "effect": "Deny",
        },
    ]
    
    cpm_rules = [
        normalizer.normalize_xacml_rule(sample_rules[0], "GDPR"),
        normalizer.normalize_xacml_rule(sample_rules[1], "PSD2"),
        normalizer.normalize_xacml_rule(sample_rules[2], "INTERNAL_SECURITY"),
    ]
    
    print("\n1. Rego Policy Generation:")
    print("-" * 50)
    
    rego_gen = RegoGenerator(package_name="policyguard.access")
    rego_policy = rego_gen.generate(cpm_rules, framework="PolicyGuard")
    
    print(rego_policy[:1500] + "...\n[truncated]")
    
    print("\n2. XACML Policy Generation:")
    print("-" * 50)
    
    xacml_gen = XACMLGenerator(policy_set_id="PolicyGuardResolvedPolicySet")
    xacml_policy = xacml_gen.generate(cpm_rules)
    
    print(xacml_policy[:1500] + "...\n[truncated]")
    
    print("\n3. Test Case Generation (from witness):")
    print("-" * 50)
    
    sample_witness = {
        "request": {
            "subject": "customer",
            "roles": ["user", "account_holder"],
            "action": "read",
            "resource": "balance_api",
            "resource_type": "account_data",
            "environment": {"authenticated": True}
        },
        "conflict": {
            "rule_i": "PSD2_001",
            "effect_i": "Permit",
            "rule_j": "SECURITY_001",
            "effect_j": "Deny"
        }
    }
    
    test_gen = TestCaseGenerator()
    opa_test = test_gen.generate_opa_test(sample_witness, "balance_access")
    print(opa_test)
    
    json_test = test_gen.generate_json_test_case(sample_witness)
    print("\nJSON Test Case:")
    print(json.dumps(json_test, indent=2))
    
    return rego_policy, xacml_policy


if __name__ == "__main__":
    demonstrate_code_generation()
